#!/bin/bash

# Colors
WHITE="\033[1;37m"
CYAN="\033[0;36m"
NC='\033[0m' # No Color

# Gather system info
product=$(cat /sys/devices/virtual/dmi/id/product_name)
BoardName=$(cat /sys/devices/virtual/dmi/id/board_name)
mem=$(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))
cpumodel=$(lscpu | grep 'Model name' | cut -f 2 -d ":" | awk '{$1=$1}1')
readarray -t gpuarray <<< $(lspci | grep VGA | cut -d ":" -f3 | cut -d " " -f 2-)
os=$(cat /etc/*-release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/"//g')
kernel=$(uname -r)
proc=$(nproc)

echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)"
echo -e "${CYAN}+ Device    ==> ${WHITE}$product"
echo -e "${CYAN}+ MBoard    ==> ${WHITE}$BoardName"
echo -e "${CYAN}+ Total RAM ==> ${WHITE}$mem Mb"
for gpu in "${gpuarray[@]}"; do
    echo -e "${CYAN}+ GPU Model ==> ${WHITE}$gpu"
done
echo -e "${CYAN}+ CPU Model ==> ${WHITE}$cpumodel"
echo -e "${CYAN}+ CPU(s)    ==> ${WHITE}$proc"
echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)"
echo -e "${CYAN}+ Distro ==> ${WHITE}$os"
echo -e "${CYAN}+ Kernel ==> ${WHITE}$kernel"
echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)${NC}"
