#!/bin/bash

# Colors
WHITE="\033[1;37m"
CYAN="\033[0;36m"
NC='\033[0m' # No Color

# Gather system info
mem=$(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / (1024 * 1024)))
cpumodel=$(lscpu | grep 'Model name' | cut -f 2 -d ":" | awk '{$1=$1}1')
readarray -t gpuarray <<< $(lspci | grep VGA | cut -d ":" -f3 | cut -d " " -f 2-)
RAM=$(cardid=$(lspci | grep VGA |cut -d " " -f1);lspci -v -s $cardid | grep " prefetchable"| cut -d "=" -f2)
os=$(cat /etc/*-release | grep "PRETTY_NAME" | sed 's/PRETTY_NAME=//g' | sed 's/"//g')
kernel=$(uname -r)
proc=$(nproc)
uptime=$(uptime)
date=$(date)

echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)"
echo -e "${CYAN}+ Total RAM ==> ${WHITE}$mem mb"
for gpu in "${gpuarray[@]}"; do
    echo -e "${CYAN}+ GPU Model ==> ${WHITE}$gpu"
done
echo -e "${CYAN}+ CPU Model ==> ${WHITE}$cpumodel"
echo -e "${CYAN}+ CPU(s)    ==> ${WHITE}$proc"
echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)"
echo -e "${CYAN}+ Distro ==> ${WHITE}$os"
echo -e "${CYAN}+ Kernel ==> ${WHITE}$kernel"
echo -e "${CYAN}+ Date   ==> ${WHITE}$date"
echo -e "${CYAN}+ Uptime ==> ${WHITE}$uptime"
echo -e "${CYAN}$(printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' +)${NC}"
